#!/bin/bash

THESAURUSDIR=~/.vim/thesaurus
THESAURUS=~/.vim/thesaurus/mthesaur.txt

[ ! -d $THESAURUSDIR ] && mkdir $THESAURUSDIR;
if [ ! -f $THESAURUS ]; then
  curl https://www.gutenberg.org/files/3202/files/mthesaur.txt -o $THESAURUS
fi

BACKUPDIR=~/.vim/backupfiles
SWAPDIR=~/.vim/swapfiles
UNDODIR=~/.vim/undodir

if [ ! -d $BACKUPDIR ]; then
  mkdir $BACKUPDIR
fi

if [ ! -d $SWAPDIR ]; then
  mkdir $SWAPDIR
fi

if [ ! -d $UNDODIR ]; then
  mkdir $UNDODIR
fi
