#!/bin/bash

THESAURUSDIR=~/.vim/thesaurus
THESAURUS=~/.vim/thesaurus/mthesaur.txt

[ ! -d $THESAURUSDIR ] && mkdir $THESAURUSDIR;
if [ ! -f $THESAURUS ]; then
  echo "saving thesaurus..."
  curl https://www.gutenberg.org/files/3202/files/mthesaur.txt -o $THESAURUS
fi

BACKUPDIR=~/.vim/backupfiles
SWAPDIR=~/.vim/swapfiles
UNDODIR=~/.vim/undodir

if [ ! -d $BACKUPDIR ]; then
  echo -n "making backup dir..."
  mkdir $BACKUPDIR
  echo "done!"
fi

if [ ! -d $SWAPDIR ]; then
  echo -n "making swap dir..."
  mkdir $SWAPDIR
  echo "done!"
fi

if [ ! -d $UNDODIR ]; then
  echo -n "making undo dir..."
  mkdir $UNDODIR
  echo "done!"
fi
