#!/usr/bin/env bash

DIR=~/.vim/thesaurus
FILE=~/.vim/thesaurus/mthesaur.txt

[ ! -d $DIR ] && mkdir ~/.vim/thesaurus;
if [ ! -f $FILE ]; then
  echo "saving thesaurus..."
  curl https://www.gutenberg.org/files/3202/files/mthesaur.txt -o ~/.vim/thesaurus/mthesaur.txt;
fi
